apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.patterdale.config.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app_name: {{ .Values.patterdale.name }}
    app_version: {{ .Values.patterdale.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  patterdale.yml: |
{{- include "patterdale.yml" . | indent 4 -}}
