apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Chart.Version | quote }}
    environment: {{ .Values.cluster.environment }}
    dev_team_responsible: {{ .Values.team }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  passwords.yml: |
{{- include "passwords.yml" . | indent 4 -}}
