apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.patterdale.passwords.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app_name: {{ .Values.patterdale.name }}
    app_version: {{ .Values.patterdale.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  passwords.yml: |
{{ include "passwords.yml" . | b64enc | indent 4 }}
