namespace: utils
team: support
role: live

patterdale:
  name: patterdale
  targetPort: 7000
  servicePort: 7000
  cacheDuration: 60

  config:
    name: patterdale-config

  passwords:
    name: passwords-config

  replicas: 1

  pool:
    maxSize: 5
    minIdle: 1

  image:
    repository: docker.io
    name: tjheslin1/patterdale
    tag: "0.13.0"
    pullPolicy: IfNotPresent

  terminationGracePeriodSeconds: 30

probes:
  - name: healthCheck
    type: exists
    query: SELECT 1 FROM DUAL
    metricName: database_up
    metricLabels: database="myDB",query="SELECT 1 FROM DUAL"
  - name: slowestQueries
    type: list
    metricName: slowest_queries
    metricLabels: sqlText="%s",sqlId="%s",username="%s",childNumber="%s",diskReads="%s",executions="%s",firstLoadTime="%s",lastLoadTime="%s"
    query: |
      SELECT * FROM
      (SELECT
          s.elapsed_time / s.executions / 1000 AS AVG_ELAPSED_TIME_IN_MILLIS,
          SUBSTR(s.sql_fulltext, 1, 80) AS SQL_TEXT,
          s.sql_id,
          d.username,
          s.child_number,
          s.disk_reads,
          s.executions,
          s.first_load_time,
          s.last_load_time
      FROM    v$sql s, dba_users d
      WHERE   s.parsing_user_id = d.user_id
      AND trunc(TO_DATE(s.last_load_time, 'YYYY-MM-DD/HH24:MI:SS')) >= trunc(SYSDATE - 1)
      ORDER BY elapsed_time DESC)
      WHERE ROWNUM <= 5;
