namespace: sky-mobile
team: deployment-and-operations-support
role: live

patterdale:
  name: patterdale
  targetPort: 7000
  cacheDuration: 60

  config:
    name: patterdale-config

  passwords:
    name: passwords-config

  replicas: 1

  pool:
    maxSize: 5
    minIdle: 1

  image:
    repository: docker.io
    name: tjheslin1/patterdale
    tag: "0.10"
    pullPolicy: IfNotPresent

  terminationGracePeriodSeconds: 30
